import axios, { AxiosRequestConfig, AxiosResponseHeaders } from 'axios';
import { v4 as uuid } from 'uuid';

import { AIPacaApi } from './lib/AIPacaApi'
import { BlockApi } from './lib/blockApi'
import { CallApi } from './lib/callApi'
import { CassandraApi } from './lib/cassandraApi'
import { ChatApi } from './lib/chatApi'
import { ConfigApi } from './lib/configApi'
import { GameApi } from './lib/gameApi'
import { GiftApi } from './lib/giftApi'
import { GroupApi } from './lib/groupApi'
import { HiddenApi } from './lib/hiddenApi'
import { LoginApi } from './lib/loginApi'
import { MiscApi } from './lib/miscApi'
import { MuteKeywordApi } from './lib/muteKeywordApi'
import { PostApi } from './lib/postApi'
import { ReviewApi } from './lib/reviewApi'
import { ThreadApi } from './lib/threadApi'
import { UserApi } from './lib/userApi'
